# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    # continue-on-error: true
    timeout-minutes: 5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: restore package
        shell: cmd
        run: |
          nuget restore LoggerTest\LoggerTest.sln

      - name: Setup MSBuild Path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: check_msbuild
        shell: cmd
        run: |
          where msbuild
          msbuild -version

      # - name: build
      #   shell: cmd
      #   run: |
      #     msbuild LoggerTest\LoggerTest.sln -maxCpuCount -target:Build -property:Platform=x64;Configuration=Release
      #     msbuild LoggerTest\LoggerTest.sln -maxCpuCount -target:Build -property:Platform=x86;Configuration=Release

      # - name: run_x86
      #   shell: cmd
      #   run: msbuild LoggerTest\LoggerTest.sln -maxCpuCount -target:Build -property:Platform=x86;Configuration=Debug -logger:LoggerTest\LoggerTest\build\x86\Release\net6.0\LoggerTest.dll

      # - name: run_x64
      #   shell: cmd
      #   run: msbuild LoggerTest\LoggerTest.sln -maxCpuCount -target:Build -property:Platform=x64;Configuration=Release -logger:LoggerTest\LoggerTest\build\x64\Release\net6.0\LoggerTest.dll

      - name: build
        shell: cmd
        run: msbuild LoggerTest\LoggerTest.sln -maxCpuCount -target:Build -property:Platform=x64;Configuration=Release

      - name: run_x64
        shell: cmd
        run: msbuild UseTest.vcxproj

